import { ViewListIcon } from "@heroicons/react/solid";

const obj = {
  title: "Legal Structure",
  desc: "Should your business be an LLC, a charity, a sole proprietorship or something else?",
  category: "Business",
  Icon: ViewListIcon,
  // tags: [],
  permissions: ["user"],

  fromColor: "gray-500",
  toColor: "gray-500",

  to: "/ai/law/legalStructure",
  api: "/ai/law/legalStructure",

  output: {
    title: "Legal Structure",
    desc: "I am Roman. An AI lawyer. I can help you understand the legal structure of your business.",
    Icon: false,
    color: "blue",
  },

  prompts: [
    {
      title: "Business Information",
      desc: "Answer a few questions about your business",
      // n: 1,
      prompts: [
        {
          title: "Business Name",
          attr: "name",
          value: "",
          placeholder: "Acne Inc.",
          label: "Examples: Jackson and Sons, Pandora Studios, Acne Ltd",
          //type: "textarea",
          maxLength: 50,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "Pluto Media ",
        },
        {
          title: "Amount of Employees",
          attr: "employees",
          value: "",
          placeholder: "three full time and two part time",
          label: "Examples: 5, twelve, three full time and two part time",
          //type: "textarea",
          maxLength: 50,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "9 ",
        },
        {
          title: "What is your annual revenue",
          attr: "revenue",
          value: "",
          placeholder: "$4,000,000",
          label: "Examples: twenty thousand, $100,000, $1,000,000",
          //type: "textarea",
          maxLength: 50,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "$33,000,000 US ",
        },
        {
          title: "Do you have a physical location",
          attr: "location",
          value: "",
          placeholder: "My basement",
          label: "Examples: online only, We Work Space, office space",
          //type: "textarea",
          maxLength: 100,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "14 Pewter Street, Rhode Island ",
        },
        {
          title: "What industry are you in?",
          attr: "industry",
          value: "",
          placeholder: "Technology",
          label: "Examples: Entertainment, Finance, Furniture",
          //type: "textarea",
          maxLength: 100,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "Marketing ",
        },
        {
          title: "Describe your business and any other relevant concern",
          attr: "content",
          value: "",
          placeholder: "I would like my son to inherit it when I retire.",
          label: "Examples: Entertainment, Finance, Furniture",
          type: "textarea",
          maxLength: 300,
          // max: 100,
          min: 3,
          required: true,
          error: "",
          example: "Marketing ",
        },
      ],
      example: {
        output:
          "Based on the information given. Your business should be an LLC ",
        // outputs: [
        // 	"The sun is very old, over 4.5 billion years",
        // 	"At 10,000 degrees, sun is also very hot",
        // 	"Gasses called coronal mass ejections erupt from the sun",
        // ],
        // Icon: RefreshIcon,
        color: "blue",
      },
    },
  ],
};

export default obj;
